Repository cnstll/ft_transcendAnce, pull requests merged in 2022-11, with the labels that each got.

#115 fix console errors by adding env variable to docker compose
  docker-compose.yaml
Labels: bug

#117 116 bug rotate api key
  backend/app/.env.dev.gpg
  backend/app/.env.gpg
  backend/app/.env.test.gpg
Labels: bug

#118 101 bug issue when user refuses to connect with 42 api
  backend/app/.env.dev.gpg
  backend/app/.env.gpg
  backend/app/.env.test.gpg
  backend/app/src/auth/auth.controller.ts
  backend/app/src/auth/middleware/api.filter.ts
Labels: bug

#113 111 us create and join rooms to send messages
  .DS_Store
  backend/app/package-lock.json
  backend/app/package.json
  backend/app/src/channel/channel.gateway.spec.ts
  backend/app/src/channel/channel.gateway.ts
  backend/app/src/channel/channel.module.ts
  backend/app/src/channel/channel.service.ts
  backend/app/src/channel/dto/joinChannel.dto.ts
  backend/app/src/channel/dto/leaveChannel.dto.ts
  backend/app/src/channel/dto/userMessage.dto.ts
  backend/app/src/strategy/jwt.strategy.ts
  backend/app/src/user/user.controller.ts
  package-lock.json
  package.json
Labels: enhancement

#112 20 us as a user i want to play the pong game in real time
  backend/app/package-lock.json
  backend/app/package.json
  backend/app/src/app.module.ts
  backend/app/src/pong/dto/position.dto.ts
  backend/app/src/pong/entities/game.entities.ts
  backend/app/src/pong/game.gateway.ts
  backend/app/src/pong/game.module.ts
  backend/app/src/pong/game.service.ts
  backend/app/src/strategy/jwt.strategy.ts
  frontend/.DS_Store
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/App.tsx
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/global-components/play.tsx
  frontend/app/src/components/section-components/canvas.tsx
  frontend/app/src/components/section-components/socket.ts
Labels: enhancement

#114 95 us as a user i want to use 2fa
  backend/app/package-lock.json
  backend/app/package.json
  backend/app/src/2fa/two.factor.authentication.controller.ts
  backend/app/src/2fa/two.factor.authentication.module.ts
  backend/app/src/2fa/two.factor.authentication.service.ts
  backend/app/src/app.module.ts
  backend/app/src/auth/auth.controller.ts
  backend/app/src/auth/auth.module.ts
  backend/app/src/auth/auth.service.ts
  backend/app/src/auth/guard/twoFa.auth-guard.ts
  backend/app/src/auth/types/jwtPayload.type.ts
  backend/app/src/auth/types/userPayload.type.ts
  backend/app/src/channel/channel.gateway.ts
  backend/app/src/main.ts
  backend/app/src/strategy/2fa.strategy.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/App.tsx
  frontend/app/src/components/global-components/2fa-sign-in.tsx
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/query-hooks/set2fa.tsx
  frontend/app/src/components/query-hooks/useQRCode.tsx
  frontend/app/src/components/section-components/my-match-history.tsx
  frontend/app/src/components/section-components/my-profile.tsx
  frontend/app/src/components/section-components/navbar.tsx
  frontend/app/src/components/section-components/nickname-form.tsx
  frontend/app/src/components/section-components/their-match-history.tsx
  frontend/app/src/components/section-components/their-profile.tsx
  frontend/app/src/components/section-components/two-factor-authentication.tsx
  frontend/app/src/components/section-components/upload-picture.tsx
  frontend/app/src/custom.d.ts
  frontend/app/tailwind.config.js
Labels: enhancement

#122 21 us as a player i want to win the game when i hit 10 points
  backend/app/src/pong/entities/game.entities.ts
Labels: enhancement

#120 102 us i want to create any type of channels from a form in the chat
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/global-components/profile.tsx
  frontend/app/src/components/query-hooks/useCreateChannel.tsx
  frontend/app/src/components/query-hooks/useCreateFriendship.tsx
  frontend/app/src/components/query-hooks/useGetChannels.tsx
  frontend/app/src/components/section-components/all-channels-list.tsx
  frontend/app/src/components/section-components/channel-header.tsx
  frontend/app/src/components/section-components/channels-list-item.tsx
  frontend/app/src/components/section-components/channels-list.tsx
  frontend/app/src/components/section-components/create-channel-form.tsx
  frontend/app/src/components/section-components/my-channels-list.tsx
  frontend/app/src/components/section-components/nickname-form.tsx
  frontend/app/src/components/section-components/profile-box.tsx
  frontend/app/src/components/section-components/search-box.tsx
  frontend/app/src/components/section-components/search-item.tsx
Labels: enhancement

#130 92 bug can add yourself as friend
  frontend/app/src/components/global-components/profile.tsx
  frontend/app/src/components/section-components/canvas.tsx
  frontend/app/src/components/section-components/channels-list.tsx
  frontend/app/src/components/section-components/my-profile.tsx
  frontend/app/src/components/section-components/profile-box.tsx
Labels: bug

#132 Not sharing keys between different requests is definitely a better id…
  frontend/app/src/components/query-hooks/useGetAllUsers.tsx
Labels: bug

#135 fixed get target data endpoint and clarified naming one findOne methods
  backend/app/src/auth/auth.service.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
Labels: bug

#137 added endpoints to get leaderboard + user ranking
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
Labels: enhancement

#138 Regex check for inputs in channel creation form
  frontend/app/src/components/section-components/chat/create-channel-form.tsx
Labels: enhancement

#144 fixes issue with the disconnecting player winning the game
  backend/app/src/pong/game.service.ts
Labels: bug

#150 adding a loading spinner to all loading state + adding some error states
  frontend/app/src/components/global-components/profile.tsx
  frontend/app/src/components/section-components/chat/channel-header.tsx
  frontend/app/src/components/section-components/chat/my-channels-list.tsx
  frontend/app/src/components/section-components/friend-list.tsx
  frontend/app/src/components/section-components/loading-spinner.tsx
  frontend/app/src/components/section-components/profile/my-profile.tsx
  frontend/app/src/components/section-components/profile/stats-box.tsx
  frontend/app/src/components/section-components/profile/their-profile.tsx
Labels: enhancement

#149 145 bug leaving a game when in the waiting room causes issues in the backend
  backend/app/src/pong/dto/position.dto.ts
  backend/app/src/pong/entities/game.entities.ts
  backend/app/src/pong/game.gateway.ts
  backend/app/src/pong/game.service.ts
  frontend/app/src/components/section-components/play/canvas.tsx
Labels: bug

#148 124 us as a dev i want to hash channel passwords
  backend/app/package-lock.json
  backend/app/package.json
  backend/app/src/channel/channel.service.ts
  package-lock.json
  package.json
Labels: enhancement

#142 14 us as a user i want to have a match history
  backend/app/src/user/dto/stats.dto.ts
  backend/app/src/user/interfaces/matchHistory.interface.ts
  backend/app/src/user/interfaces/stats.interface.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/global-components/profile.tsx
  frontend/app/src/components/query-hooks/useUserMatchHistory.tsx
  frontend/app/src/components/query-hooks/useUserStats.tsx
  frontend/app/src/components/section-components/profile/match-history.tsx
  frontend/app/src/components/section-components/profile/my-match-history.tsx
  frontend/app/src/components/section-components/profile/my-profile.tsx
  frontend/app/src/components/section-components/profile/stats-box.tsx
  frontend/app/src/components/section-components/profile/their-match-history.tsx
  frontend/app/src/components/section-components/profile/their-profile.tsx
  frontend/app/src/components/section-components/profile/two-factor-authentication.tsx
  frontend/app/src/components/section-components/search-box.tsx
  frontend/app/src/components/section-components/search-item.tsx
Labels: enhancement

#139 31 us as a user i want to join and leave channels
  backend/app/src/channel/channel.controller.ts
  backend/app/src/channel/channel.gateway.ts
  backend/app/src/channel/channel.service.ts
  backend/app/src/channel/dto/joinChannel.dto.ts
  backend/app/src/channel/dto/leaveChannel.dto.ts
  backend/app/test/channel.e2e-spec.ts
  frontend/app/src/App.tsx
  frontend/app/src/components/custom-hooks/emit-join-channel.tsx
  frontend/app/src/components/custom-hooks/norm-url.tsx
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/client-socket.ts
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/query-hooks/useGetChannels.tsx
  frontend/app/src/components/section-components/chat/channel-header.tsx
  frontend/app/src/components/section-components/chat/channel-options.tsx
  frontend/app/src/components/section-components/chat/channels-list-item.tsx
  frontend/app/src/components/section-components/chat/channels-list.tsx
  frontend/app/src/components/section-components/chat/create-channel-form.tsx
  frontend/app/src/components/section-components/chat/my-channels-list.tsx
  frontend/app/src/components/section-components/chat/search-channel-item.tsx
  frontend/app/src/components/section-components/navbar.tsx
  frontend/app/src/components/section-components/play/canvas.tsx
  frontend/app/src/components/section-components/search-box-channel.tsx
  frontend/app/src/components/section-components/search-box-user.tsx
  frontend/app/src/components/section-components/search-item.tsx
  frontend/app/src/components/section-components/search-user-item.tsx
  frontend/app/src/components/section-components/users-list-item.tsx
Labels: enhancement

#157 Removing required env fields
  .github/ISSUE_TEMPLATE/bug.yml
Labels: enhancement

#151 28 us as a player i want to have map options for my game
  backend/app/src/pong/entities/game.entities.ts
  backend/app/src/pong/game.gateway.ts
  backend/app/src/pong/game.service.ts
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/global-components/play.tsx
  frontend/app/src/components/section-components/play/canvas.tsx
Labels: enhancement

#158 added a leaveGame listener for when the user navigates away from a ga…
  backend/app/src/pong/game.gateway.ts
  frontend/app/src/components/section-components/play/canvas.tsx
Labels: bug

#161 Ranking
  backend/app/src/pong/game.service.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/global-components/ranking.tsx
  frontend/app/src/components/query-hooks/useGetAllUsers.tsx
  frontend/app/src/components/query-hooks/useLeaderboard.tsx
  frontend/app/src/components/query-hooks/useTargetInfo.tsx
  frontend/app/src/components/query-hooks/useUserMatchHistory.tsx
  frontend/app/src/components/query-hooks/useUserStats.tsx
  frontend/app/src/components/section-components/friend-status.tsx
  frontend/app/src/components/section-components/profile/match-history.tsx
  frontend/app/src/components/section-components/profile/stats-box.tsx
  frontend/app/src/components/section-components/profile/their-profile.tsx
Labels: enhancement

#162 Change navbar responsive
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/home.tsx
  frontend/app/src/components/global-components/navbar.tsx
  frontend/app/src/components/global-components/play.tsx
  frontend/app/src/components/global-components/profile.tsx
  frontend/app/src/components/global-components/ranking.tsx
  frontend/app/src/components/section-components/search-box-channel.tsx
  frontend/app/src/components/section-components/search-box-user.tsx
Labels: bug

#171 Achievements
  backend/app/prisma/migrations/20221111140958_20221111/migration.sql
  backend/app/prisma/migrations/20221112224743_20221112/migration.sql
  backend/app/prisma/schema.prisma
  backend/app/prisma/seed.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/query-hooks/useUserAchievements.tsx
  frontend/app/src/components/section-components/chat/create-channel-form.tsx
  frontend/app/src/components/section-components/chat/edit-channel-form.tsx
  frontend/app/src/components/section-components/profile/achievement.tsx
  frontend/app/src/components/section-components/profile/my-profile.tsx
  frontend/app/src/components/section-components/profile/their-profile.tsx
  frontend/app/src/components/section-components/profile/two-factor-authentication.tsx
Labels: enhancement

#169 107 I want to send and receive messages
  backend/app/package-lock.json
  backend/app/package.json
  backend/app/src/channel/channel.controller.ts
  backend/app/src/channel/channel.gateway.ts
  backend/app/src/channel/channel.service.ts
  backend/app/src/channel/dto/incomingMessage.dto.ts
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/query-hooks/useGetChannelUsers.tsx
  frontend/app/src/components/query-hooks/useGetMessages.tsx
  frontend/app/src/components/section-components/chat/channel-header.tsx
  frontend/app/src/components/section-components/chat/channel-options.tsx
  frontend/app/src/components/section-components/chat/chat-box.tsx
  frontend/app/src/components/section-components/chat/create-channel-form.tsx
  frontend/app/src/components/section-components/chat/display-messages.tsx
  frontend/app/src/components/section-components/chat/message.tsx
  frontend/app/src/components/section-components/search-box-channel.tsx
Labels: enhancement

#185 The shortest commit in my all life
  frontend/app/src/components/section-components/chat/channels-list.tsx
Labels: bug

#186 Text now wrapped in chat bubble
  frontend/app/src/components/section-components/chat/display-messages.tsx
Labels: enhancement

#175 147 us as a user i want to enter a password to join protected channel
  backend/app/prisma/seed.ts
  backend/app/src/channel/channel.gateway.ts
  backend/app/src/channel/channel.service.ts
  backend/app/src/channel/dto/index.ts
  frontend/app/src/components/global-components/ranking.tsx
  frontend/app/src/components/section-components/chat/channel-options.tsx
  frontend/app/src/components/section-components/chat/edit-channel-form.tsx
  frontend/app/src/components/section-components/chat/password-modal.tsx
  frontend/app/src/components/section-components/chat/search-channel-item.tsx
  frontend/app/src/components/section-components/search-box-channel.tsx
Labels: enhancement

#192 fix(search bar): fix channel search bar
  frontend/app/src/components/section-components/search-box-channel.tsx
Labels: bug

#183 19 us as a user i want to see my friends status online offline playing
  backend/app/src/app.module.ts
  backend/app/src/user/socketToUserIdStorage.service.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.gateway.ts
  backend/app/src/user/user.module.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/client-socket.ts
  frontend/app/src/components/global-components/navbar.tsx
  frontend/app/src/components/section-components/friend-list.tsx
Labels: enhancement

#191 176 bug 2fa doesnt work on first attempt
  backend/app/src/2fa/two.factor.authentication.controller.ts
  backend/app/src/2fa/two.factor.authentication.service.ts
  backend/app/src/channel/dto/index.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/profile.tsx
  frontend/app/src/components/query-hooks/set2fa.tsx
  frontend/app/src/components/query-hooks/useQRCode.tsx
  frontend/app/src/components/query-hooks/useUserMatchHistory.tsx
  frontend/app/src/components/section-components/profile/match-history.tsx
  frontend/app/src/components/section-components/profile/two-factor-authentication.tsx
Labels: bug

#196 fix(chat): if a user is not connected and he enters an url to access …
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/profile.tsx
Labels: bug

#198 41 us as a chat user i want to see the users of a channel and go to their profile
  backend/app/src/channel/channel.service.ts
  backend/app/src/channel/dto/index.ts
  frontend/app/src/components/global-components/chat.tsx
Labels: enhancement

#200 problem solved with linux power
  backend/app/src/channel/dto/createChannel.dto.ts
  backend/app/src/channel/dto/editChannel.dto.ts
Labels: bug

#204 Removing ban component from friends options
  frontend/app/src/components/section-components/users-list-item.tsx
Labels: bug

#195 fix(search box): search box fixed
  frontend/app/src/components/section-components/search-box-channel.tsx
  frontend/app/src/components/section-components/search-box-user.tsx
Labels: bug

#212 fix getting the avatar from the modified 42 api
  backend/app/src/auth/auth.service.ts
  backend/app/src/auth/dto/auth.dto.ts
Labels: bug

#213 fix(match history): match history is fixed
  backend/app/avatar/VCERv0o-minimalist-wallpapers.png
  backend/app/src/user/user.service.ts
Labels: bug

#216 fix(ranking): ranking box now overflows
  frontend/app/src/components/section-components/one-box.tsx
Labels: bug

#218 fixed connect to use the userOnChannel relation instead of channel
  backend/app/src/channel/channel.gateway.ts
  backend/app/src/channel/channel.service.ts
Labels: bug

#208 add timeout to volatile emit to make sure no outdated game info is re…
  backend/app/src/pong/game.service.ts
Labels: enhancement

#221 fix(game): fix ending message
  backend/app/src/pong/entities/game.entities.ts
  backend/app/src/pong/game.service.ts
  frontend/app/src/components/section-components/play/canvas.tsx
Labels: bug

#214 33 us as a user i want to create a private channel and invite users on it
  backend/app/.env.dev.gpg
  backend/app/.env.gpg
  backend/app/.env.prod.gpg
  backend/app/.env.test.gpg
  backend/app/prisma/migrations/20221122125343_add_invites/migration.sql
  backend/app/prisma/schema.prisma
  backend/app/prisma/seed.ts
  backend/app/src/channel/channel.controller.ts
  backend/app/src/channel/channel.gateway.spec.ts
  backend/app/src/channel/channel.gateway.ts
  backend/app/src/channel/channel.service.ts
  backend/app/src/channel/dto/inviteChannel.dto.ts
  backend/app/src/channel/dto/joinChannel.dto.ts
  frontend/app/src/components/custom-hooks/emit-join-channel.tsx
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/query-hooks/getChannelInvites.tsx
  frontend/app/src/components/query-hooks/useGetChannels.tsx
  frontend/app/src/components/section-components/chat/channel-options.tsx
  frontend/app/src/components/section-components/chat/edit-channel-form.tsx
  frontend/app/src/components/section-components/chat/invite-modal.tsx
  frontend/app/src/components/section-components/chat/password-modal.tsx
  frontend/app/src/components/section-components/search-box-channel.tsx
  frontend/app/src/components/section-components/search-box-user.tsx
Labels: enhancement

#229 24 us as a user i want to watch an ongoing game between two other players
  backend/app/.env.dev.gpg
  backend/app/.env.gpg
  backend/app/.env.prod.gpg
  backend/app/.env.test.gpg
  backend/app/src/user/user.gateway.ts
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/global-components/navbar.tsx
  frontend/app/src/components/global-components/profile.tsx
  frontend/app/src/components/section-components/block-friends.tsx
  frontend/app/src/components/section-components/chat/invite-modal.tsx
  frontend/app/src/components/section-components/chat/members-list.tsx
  frontend/app/src/components/section-components/chat/members-options.tsx
  frontend/app/src/components/section-components/friend-list.tsx
  frontend/app/src/components/section-components/invite-to-play.tsx
  frontend/app/src/components/section-components/profile/friends-list.tsx
  frontend/app/src/components/section-components/profile/friends-options.tsx
  frontend/app/src/components/section-components/users-list-item.tsx
  frontend/app/src/components/section-components/users-list.tsx
  frontend/app/src/components/section-components/watch-game.tsx
Labels: bug

#234 Chat automatically scroll down to last sent message
  frontend/app/src/components/global-components/chat.tsx
Labels: bug

#219 fallback page for url chat
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/navbar.tsx
  frontend/app/src/components/section-components/chat/channel-options.tsx
  frontend/app/src/components/section-components/chat/display-messages.tsx
Labels: bug

#206 a player now leaves the queue if he quite the pending page before a g…
  backend/app/src/pong/entities/game.entities.ts
  backend/app/src/pong/game.service.ts
Labels: bug

#223 fix(2fa): delete 2faSecret from the interface
  backend/app/src/channel/channel.service.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/query-hooks/useGetAllUsers.tsx
  frontend/app/src/components/query-hooks/useUserInfo.tsx
Labels: bug

#236 feat(db): change database for mute, ban and block
  backend/app/prisma/migrations/20221124104532_channel_action/migration.sql
  backend/app/prisma/schema.prisma
Labels: enhancement

#240 invalidating channel user list
  frontend/app/src/components/global-components/navbar.tsx
Labels: bug

#233 40 us as a chat user i want to invite other users to play pong game
  backend/app/.env.dev.gpg
  backend/app/.env.gpg
  backend/app/.env.prod.gpg
  backend/app/.env.test.gpg
  backend/app/src/pong/entities/game.entities.ts
  backend/app/src/pong/game.gateway.ts
  backend/app/src/pong/game.module.ts
  backend/app/src/pong/game.service.ts
  backend/app/src/user/socketToUserIdStorage.service.ts
  backend/app/src/user/user.gateway.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/global-components/navbar.tsx
  frontend/app/src/components/section-components/invite-to-play.tsx
  frontend/app/src/components/section-components/play/canvas.tsx
  frontend/app/src/components/section-components/profile/friends-options.tsx
Labels: enhancement

#243 201 bug leaving a channel does not end well
  backend/app/.env.dev.gpg
  backend/app/.env.gpg
  backend/app/.env.prod.gpg
  backend/app/.env.test.gpg
  backend/app/src/channel/channel.controller.ts
  backend/app/src/channel/channel.service.ts
  frontend/app/src/components/query-hooks/useGetChannelAuthors.tsx
  frontend/app/src/components/section-components/chat/display-messages.tsx
Labels: bug

#247 156 bug can access yourself in search bar
  frontend/app/src/components/global-components/navbar.tsx
  frontend/app/src/components/section-components/search-box-user.tsx
Labels: bug

#232 167 bug when i go on a channel through url i should be reconnected to the socket or see 404
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/global-components/page-not-found.tsx
  frontend/app/src/components/global-components/play.tsx
  frontend/app/src/components/global-components/profile.tsx
Labels: bug

#241 228 us refacto game logic in front
  backend/app/.env.dev.gpg
  backend/app/.env.gpg
  backend/app/.env.prod.gpg
  backend/app/.env.test.gpg
  backend/app/src/pong/game.gateway.ts
  backend/app/src/pong/game.service.ts
  frontend/app/src/App.tsx
  frontend/app/src/components/custom-hooks/draw.tsx
  frontend/app/src/components/custom-hooks/game-statuses.tsx
  frontend/app/src/components/global-components/interface.tsx
  frontend/app/src/components/global-components/play.tsx
  frontend/app/src/components/global-components/watch.tsx
  frontend/app/src/components/section-components/chat/members-options.tsx
  frontend/app/src/components/section-components/game/canvas.tsx
  frontend/app/src/components/section-components/game/watch-game.tsx
  frontend/app/src/components/section-components/play/canvas.tsx
  frontend/app/src/components/section-components/profile/friends-options.tsx
  frontend/app/src/components/section-components/watch-game-options.tsx
Labels: enhancement

#250 249 bug on leaving channel channel is not removed from channel list
  frontend/app/src/components/section-components/chat/channel-options.tsx
Labels: bug

#242 40 us as a chat user i want to invite other users to play pong game
  backend/app/src/pong/game.service.ts
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/components/global-components/navbar.tsx
Labels: enhancement

#255 fix error wording in password modal
  frontend/app/src/components/section-components/chat/password-modal.tsx
Labels: bug

#254 fix only display invite modal for private channel
  frontend/app/src/components/section-components/chat/channel-options.tsx
Labels: bug

#262 user that is watching the game is now redirected to the home page rat…
  frontend/app/src/components/global-components/watch.tsx
  frontend/app/src/components/section-components/game/watch-game.tsx
Labels: bug

#259 fix issue with several multiplayer games
  backend/app/src/pong/game.service.ts
Labels: bug

#270 A comprehensive first attempt at improving the game's user experience on mobile devices
  frontend/app/src/components/section-components/game/canvas.tsx
Labels: enhancement

#271 266 bug fix channel banner and issue on modals and search box
  frontend/app/src/components/global-components/chat.tsx
  frontend/app/src/components/section-components/chat/channel-header.tsx
  frontend/app/src/components/section-components/chat/search-channel-item.tsx
  frontend/app/src/components/section-components/drop-down-button.tsx
  frontend/app/src/components/section-components/search-box-channel.tsx
  frontend/app/src/components/section-components/search-box-user.tsx
  frontend/app/src/components/section-components/search-user-item.tsx
  frontend/app/src/components/section-components/users-list-item.tsx
  frontend/app/src/components/section-components/users-list.tsx
Labels: bug, enhancement

#264 226 us nth I want a not invited message for private channels
  backend/app/src/channel/channel.controller.ts
  backend/app/src/user/user.controller.ts
  backend/app/src/user/user.service.ts
  frontend/app/src/components/query-hooks/getChannelInvites.tsx
  frontend/app/src/components/section-components/chat/channels-list-item.tsx
  frontend/app/src/components/section-components/chat/edit-channel-form.tsx
  frontend/app/src/components/section-components/chat/invite-modal.tsx
  frontend/app/src/components/section-components/chat/password-modal.tsx
  frontend/app/src/components/section-components/chat/search-channel-item.tsx
  frontend/app/src/components/section-components/search-box-channel.tsx
  package-lock.json
  package.json
Labels: enhancement
